GET http://localhost:80/api/item?id=99
Accept: application/json

###




###
# POST   /g/v1/goods
# GET    /g/v1/goods/:id
# DELETE /g/v1/goods/:id
# GET    /g/v1/goods/:id/stocks
# PUT    /g/v1/goods/:id
# PATCH  /g/v1/goods/:id

GET http://localhost:8022/g/v1/goods
Accept: application/json
Content-Type: application/json

{
  "name": "商品名字",
  "goods_sn": "111",
  "stocks": 111,
  "category": 6,
  "market_price": 111,
  "shop_price": 11.1,
  "goods_brief": "商品描述",
  "images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiaomi_logo_%282021-%29.svg/512px-Xiaomi_logo_%282021-%29.svg.png"],
  "desc_images": ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiaomi_logo_%282021-%29.svg/512px-Xiaomi_logo_%282021-%29.svg.png"],
  "ship_free": true,
  "front_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Xiaomi_logo_%282021-%29.svg/512px-Xiaomi_logo_%282021-%29.svg.png",
  "brand": 6
}


###
# GET    /g/v1/categorys
# DELETE /g/v1/categorys/:id
# GET    /g/v1/categorys/:id
# POST   /g/v1/categorys
# PUT    /g/v1/categorys/:id
GET http://localhost:8022/g/v1/categorys
Accept: application/json
Content-Type: application/json

{
  "name": "三级品类2",
  "parent": 3,
  "level": 3,
  "is_tab": false,
  "id": 1,
  "level": 2
}

###
# GET    /g/v1/banner
# POST   /g/v1/banner
# DELETE /g/v1/banner/:id
# PUT    /g/v1/banner/:id
GET http://localhost:8022/g/v1/banner



####
# GET    /g/v1/brands
# DELETE /g/v1/brands/:id
# POST   /g/v1/brands
# PUT    /g/v1/brands/:id
# GET    /g/v1/categorybrands
# DELETE /g/v1/categorybrands/:id
# POST   /g/v1/categorybrands
# PUT    /g/v1/categorybrands/:id
# GET    /g/v1/categorybrands/:id
POST http://localhost:8022/g/v1/categorybrands
Accept: application/json
Content-Type: application/json

{
  "category_id": 6,
  "brand_id": 6
}



