name: 'user-web'
port: 8021
user_srv:
    host: '127.0.0.1'
    port: 50051
    name: 'user-srv'

jwt:
    key: 'signkey'

redis:
     host: '127.0.0.1'
     port: 7379
     password: 'hecvvceh'

sms:
    key: ''
    secret: ''
    expire: 5

consul:
      host: '192.168.1.175'
      port: 8500